import os
import json
import feedparser
from google import genai
from datetime import datetime, timedelta
from dotenv import load_dotenv

os.chdir(os.path.dirname(os.path.abspath(__file__)))
load_dotenv()

RSS_FEEDS = [
    "https://techcrunch.com/category/artificial-intelligence/feed/",
    "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    "https://venturebeat.com/category/ai/feed/",
    "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
]

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>今日のAIニュース - {date}</title>
  <link rel="stylesheet" href="style.css">
  <style>
    .source-row {{ display: flex; align-items: center; gap: 0.8rem; margin-top: 0.5rem; }}
    .pub-time {{ color: #6e7681; font-size: 0.78rem; white-space: nowrap; }}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>今日のAIニュース</h1>
      <p class="date">{date}</p>
    </header>
    <div class="news-grid">
{cards}
    </div>
    <div class="summary-section">
      <h3>まとめ</h3>
{summary_paragraphs}
    </div>
    <footer>
      <p>今日のAIニュース &mdash; {date} &copy; Auto-generated by Gemini</p>
    </footer>
  </div>
</body>
</html>
"""


def parse_published(entry):
    """RSSエントリから掲載日時を取得してJST文字列で返す"""
    t = entry.get("published_parsed") or entry.get("updated_parsed")
    if t:
        try:
            dt = datetime(*t[:6])
            dt_jst = dt + timedelta(hours=9)
            return dt_jst.strftime("%Y/%m/%d %H:%M")
        except Exception:
            pass
    return ""


def fetch_articles(max_per_feed=8):
    articles = []
    for url in RSS_FEEDS:
        print(f"  Fetching: {url}")
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:max_per_feed]:
                title = entry.get("title", "").strip()
                summary = entry.get("summary", entry.get("description", "")).strip()
                link = entry.get("link", "")
                published = parse_published(entry)
                if title:
                    articles.append({
                        "title": title,
                        "summary": summary[:300],
                        "url": link,
                        "published": published,
                    })
        except Exception as e:
            print(f"  [ERROR] Failed to fetch {url}: {e}")
    return articles


def generate_news_with_gemini(articles):
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY が設定されていません。")

    client = genai.Client(api_key=api_key)
    today = datetime.now().strftime("%Y年%m月%d日")

    articles_text = "\n".join(
        f"[{i+1}] タイトル: {a['title']}\n    概要: {a['summary']}\n    URL: {a['url']}\n    掲載日時: {a['published']}"
        for i, a in enumerate(articles)
    )

    prompt = (
        f"あなたはAIニュースの専門ライターです。"
        f"以下の英語記事リストを参考に、{today}の「今日のAIニュース」を日本語で20本作成してください。\n\n"
        f"【記事リスト】\n{articles_text}\n\n"
        f"【出力形式】\nJSON形式のリストのみを出力してください。\n"
        f"[\n"
        f"  {{\n"
        f"    \"number\": 1,\n"
        f"    \"title\": \"ニュースタイトル\",\n"
        f"    \"points\": [\"要点1\", \"要点2\"],\n"
        f"    \"url\": \"元記事URL\",\n"
        f"    \"published\": \"掲載日時（RSSから取得した値をそのまま使用。例: 2026/02/25 09:30）\"\n"
        f"  }},\n"
        f"  ...\n"
        f"  {{ \"summary\": [\"まとめ1\", \"まとめ2\", \"まとめ3\"] }}\n"
        f"]"
    )

    print("  Gemini APIに問い合わせ中...")
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    raw = response.text.strip()
    if "```" in raw:
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    return json.loads(raw)


def build_html(news_items, summary_lines, date_str):
    cards_html = ""
    for item in news_items:
        num = str(item.get("number", "")).zfill(2)
        title = item.get("title", "")
        points = item.get("points", [])
        url = item.get("url", "")
        published = item.get("published", "")

        points_html = "\n".join(f'        <p>{p}</p>' for p in points)

        if url:
            time_str = f'<span class="pub-time">{published}</span>' if published else ""
            source_html = f'\n        <div class="source-row">{time_str}<a class="source" href="{url}" target="_blank">元記事を読む →</a></div>'
        else:
            source_html = ""

        cards_html += (
            f'      <div class="card">'
            f'<div class="card-header"><span class="badge">{num}</span><h2>{title}</h2></div>'
            f'{points_html}{source_html}'
            f'</div>\n'
        )

    summary_paragraphs = "\n".join(f'      <p>{s}</p>' for s in summary_lines)
    return HTML_TEMPLATE.format(date=date_str, cards=cards_html, summary_paragraphs=summary_paragraphs)


def build_txt(news_items, summary_lines, date_str, fetched_at):
    lines = []
    lines.append("=" * 64)
    lines.append(f" 今日のAIニュース - {date_str}")
    lines.append(f" 取得日時: {fetched_at}")
    lines.append("=" * 64)
    lines.append("")

    for item in news_items:
        num = item.get("number", "")
        title = item.get("title", "")
        points = item.get("points", [])
        url = item.get("url", "")
        published = item.get("published", "")

        lines.append(f"【{num}】{title}")
        if published:
            lines.append(f"  掲載日時: {published}")
        for p in points:
            lines.append(f"  {p}")
        if url:
            lines.append(f"  → {url}")
        lines.append("")

    lines.append("=" * 64)
    lines.append(" まとめ")
    lines.append("=" * 64)
    lines.append("")
    for s in summary_lines:
        lines.append(s)
    lines.append("")
    lines.append("=" * 64)

    return "\n".join(lines)


def main():
    now = datetime.now()
    weekdays = ["月", "火", "水", "木", "金", "土", "日"]
    date_str = now.strftime(f"%Y年%m月%d日（{weekdays[now.weekday()]}）")
    fetched_at = now.strftime("%Y-%m-%d %H:%M:%S")
    txt_filename = now.strftime("%Y%m%d_%H%M%S") + ".txt"

    print(f"[{fetched_at}] AIニュース更新開始")

    print("RSSフィード取得中...")
    articles = fetch_articles()
    if not articles:
        print("[ERROR] 記事を取得できませんでした。")
        return
    print(f"  合計 {len(articles)} 件の記事を取得")

    print("Gemini APIでニュース生成中...")
    data = generate_news_with_gemini(articles)
    news_items = [item for item in data if isinstance(item, dict) and "title" in item]
    summary_obj = next((item for item in data if isinstance(item, dict) and "summary" in item and "title" not in item), None)
    summary_lines = summary_obj.get("summary", ["本日も多くのAIニュースが報告されました。"]) if summary_obj else ["本日も多くのAIニュースが報告されました。"]

    print(f"  {len(news_items)} 件のニュースを生成")

    # HTML出力
    html_content = build_html(news_items, summary_lines, date_str)
    with open("ai.html", "w", encoding="utf-8") as f:
        f.write(html_content)

    # TXT出力（source_textsディレクトリ）
    os.makedirs("source_texts", exist_ok=True)
    txt_content = build_txt(news_items, summary_lines, date_str, fetched_at)
    txt_path = os.path.join("source_texts", txt_filename)
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(txt_content)

    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] 完了: ai.html / source_texts/{txt_filename} を更新しました")


if __name__ == "__main__":
    main()