import os
import json
import feedparser
from google import genai
from datetime import datetime, timedelta
from dotenv import load_dotenv
from urllib.parse import urlparse

os.chdir(os.path.dirname(os.path.abspath(__file__)))
load_dotenv()

# ドメインからサイト名へのマッピング
SITE_NAMES = {
    "techcrunch.com": "TechCrunch",
    "www.theverge.com": "The Verge",
    "venturebeat.com": "VentureBeat",
    "www.technologyreview.com": "MIT Technology Review",
    "www.theguardian.com": "The Guardian",
    "www.artificialintelligence-news.com": "AI News",
    "feeds.bbci.co.uk": "BBC Politics",
    "rss.nytimes.com": "NYT Politics",
    "www.reuters.com": "Reuters Politics",
}

CATEGORY_CONFIG = {
    "ai": {
        "role": "AIニュースの専門ライター",
        "title": "今日のAIニュース",
        "html_file": "ai.html",
        "prompt_intro": "以下の英語記事リストを参考に、{today}の「今日のAIニュース」を日本語で20本作成してください。",
    },
    "politics": {
        "role": "政治ニュースの専門ライター",
        "title": "今日の政治ニュース",
        "html_file": "politics.html",
        "prompt_intro": "以下の英語記事リストを参考に、{today}の「今日の政治ニュース」を日本語で20本作成してください。",
    },
}


def get_html_template(title):
    return (
        '<!DOCTYPE html>\n'
        '<html lang="ja">\n'
        '<head>\n'
        '  <meta charset="UTF-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f'  <title>{title} - REPLACE_DATE</title>\n'
        '  <link rel="stylesheet" href="style.css">\n'
        '  <style>\n'
        '    .source-row { display: flex; align-items: center; gap: 0.8rem; margin-top: 0.5rem; }\n'
        '    .pub-time { color: #6e7681; font-size: 0.78rem; white-space: nowrap; }\n'
        '    .updated-at { color: #6e7681; font-size: 0.85rem; margin-top: 0.2rem; }\n'
        '    .site-name { color: #6e7681; font-size: 0.78rem; white-space: nowrap; }\n'
        '  </style>\n'
        '</head>\n'
        '<body>\n'
        '  <div class="container">\n'
        '    <header>\n'
        f'      <h1>{title}</h1>\n'
        '      <p class="date">REPLACE_DATE</p>\n'
        '      <p class="updated-at">最終更新：REPLACE_FETCHED_AT JST</p>\n'
        '    </header>\n'
        '    <div class="news-grid">\n'
        'REPLACE_CARDS\n'
        '    </div>\n'
        '    <div class="summary-section">\n'
        '      <h3>まとめ</h3>\n'
        'REPLACE_SUMMARY\n'
        '    </div>\n'
        '    <footer>\n'
        f'      <p>{title} &mdash; REPLACE_DATE &copy; Auto-generated by Gemini</p>\n'
        '    </footer>\n'
        '  </div>\n'
        '</body>\n'
        '</html>\n'
    )

def get_site_name(url: str) -> str:
    try:
        domain = urlparse(url).netloc
        return SITE_NAMES.get(domain, domain)
    except Exception:
        return ""


def parse_published(entry):
    t = entry.get("published_parsed") or entry.get("updated_parsed")
    if t:
        try:
            dt = datetime(*t[:6])
            dt_jst = dt + timedelta(hours=9)
            return dt_jst.strftime("%Y/%m/%d %H:%M")
        except Exception:
            pass
    return ""


def load_feeds_config():
    feeds_file = "feeds.json"
    if os.path.exists(feeds_file):
        with open(feeds_file, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


def fetch_articles(category=None):
    feeds_config = load_feeds_config()
    if category:
        feeds_config = [f for f in feeds_config if f.get("category") == category]
    articles = []
    for feed_conf in feeds_config:
        url = feed_conf["url"]
        max_items = feed_conf.get("max_items", 5)
        print(f"  Fetching: {url}")
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:max_items]:
                title = entry.get("title", "").strip()
                summary = entry.get("summary", entry.get("description", "")).strip()
                link = entry.get("link", "")
                published = parse_published(entry)
                if title:
                    articles.append({
                        "title": title,
                        "summary": summary[:300],
                        "url": link,
                        "published": published,
                    })
        except Exception as e:
            print(f"  [ERROR] Failed to fetch {url}: {e}")
    return articles


def generate_news_with_gemini(articles, category="ai"):
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY が設定されていません。")

    conf = CATEGORY_CONFIG[category]
    client = genai.Client(api_key=api_key)
    today = datetime.now().strftime("%Y年%m月%d日")

    articles_text = "\n".join(
        f"[{i+1}] タイトル: {a['title']}\n    概要: {a['summary']}\n    URL: {a['url']}\n    掲載日時: {a['published']}"
        for i, a in enumerate(articles)
    )

    prompt = (
        f"あなたは{conf['role']}です。"
        f"{conf['prompt_intro'].format(today=today)}\n\n"
        f"【記事リスト】\n{articles_text}\n\n"
        f"【出力形式】\nJSON形式のリストのみを出力してください。\n"
        f"[\n"
        f"  {{\n"
        f"    \"number\": 1,\n"
        f"    \"title\": \"ニュースタイトル\",\n"
        f"    \"points\": [\"要点1\", \"要点2\"],\n"
        f"    \"url\": \"元記事URL\",\n"
        f"    \"published\": \"掲載日時（RSSから取得した値をそのまま使用。例: 2026/02/25 09:30）\"\n"
        f"  }},\n"
        f"  ...\n"
        f"  {{ \"summary\": [\"まとめ1\", \"まとめ2\", \"まとめ3\"] }}\n"
        f"]"
    )

    print(f"  Gemini APIに問い合わせ中... (category={category})")
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    raw = response.text.strip()
    if "```" in raw:
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    return json.loads(raw)


def build_html(news_items, summary_lines, date_str, fetched_at, category="ai"):
    html_template = get_html_template(CATEGORY_CONFIG[category]["title"])
    cards_html = ""
    for item in news_items:
        num = str(item.get("number", "")).zfill(2)
        title = item.get("title", "")
        points = item.get("points", [])
        url = item.get("url", "")
        published = item.get("published", "")

        points_html = "\n".join(f'        <p>{p}</p>' for p in points)

        if url:
            time_str = f'<span class="pub-time">{published}</span>' if published else ""
            site_name = get_site_name(url)
            site_str = f'<span class="site-name">{site_name}</span>' if site_name else ""
            source_html = (
                f'\n        <div class="source-row">'
                f'{time_str}{site_str}'
                f'<a class="source" href="{url}" target="_blank">元記事を読む →</a>'
                f'</div>'
            )
        else:
            source_html = ""

        cards_html += (
            f'      <div class="card">'
            f'<div class="card-header"><span class="badge">{num}</span><h2>{title}</h2></div>'
            f'{points_html}{source_html}'
            f'</div>\n'
        )

    summary_paragraphs = "\n".join(f'      <p>{s}</p>' for s in summary_lines)
    return (html_template
            .replace("REPLACE_DATE", date_str)
            .replace("REPLACE_FETCHED_AT", fetched_at)
            .replace("REPLACE_CARDS", cards_html)
            .replace("REPLACE_SUMMARY", summary_paragraphs)
        )


def build_txt(news_items, summary_lines, date_str, fetched_at, category="ai"):
    cat_title = CATEGORY_CONFIG[category]["title"]
    lines = []
    lines.append("=" * 64)
    lines.append(f" {cat_title} - {date_str}")
    lines.append(f" 取得日時: {fetched_at}")
    lines.append("=" * 64)
    lines.append("")

    for item in news_items:
        num = item.get("number", "")
        title = item.get("title", "")
        points = item.get("points", [])
        url = item.get("url", "")
        published = item.get("published", "")

        lines.append(f"【{num}】{title}")
        if published:
            lines.append(f"  掲載日時: {published}")
        if url:
            site_name = get_site_name(url)
            if site_name:
                lines.append(f"  メディア: {site_name}")
        for p in points:
            lines.append(f"  {p}")
        if url:
            lines.append(f"  → {url}")
        lines.append("")

    lines.append("=" * 64)
    lines.append(" まとめ")
    lines.append("=" * 64)
    lines.append("")
    for s in summary_lines:
        lines.append(s)
    lines.append("")
    lines.append("=" * 64)

    return "\n".join(lines)


def process_category(category, now):
    weekdays = ["月", "火", "水", "木", "金", "土", "日"]
    date_str = now.strftime(f"%Y年%m月%d日（{weekdays[now.weekday()]}）")
    fetched_at = now.strftime("%Y-%m-%d %H:%M:%S")
    txt_filename = now.strftime("%Y%m%d_%H%M%S") + f"_{category}.txt"
    html_file = CATEGORY_CONFIG[category]["html_file"]

    print(f"\n--- {CATEGORY_CONFIG[category]['title']} 処理開始 ---")

    print("RSSフィード取得中...")
    articles = fetch_articles(category=category)
    if not articles:
        print(f"[ERROR] {category} の記事を取得できませんでした。")
        return

    print(f"  合計 {len(articles)} 件の記事を取得")
    print("Gemini APIでニュース生成中...")
    data = generate_news_with_gemini(articles, category=category)

    news_items = [item for item in data if isinstance(item, dict) and "title" in item]
    summary_obj = next((item for item in data if isinstance(item, dict) and "summary" in item and "title" not in item), None)
    summary_lines = summary_obj.get("summary", ["本日も多くのニュースが報告されました。"]) if summary_obj else ["本日も多くのニュースが報告されました。"]

    print(f"  {len(news_items)} 件のニュースを生成")

    html_content = build_html(news_items, summary_lines, date_str, fetched_at, category)
    with open(html_file, "w", encoding="utf-8") as f:
        f.write(html_content)

    os.makedirs("source_texts", exist_ok=True)
    txt_content = build_txt(news_items, summary_lines, date_str, fetched_at, category)
    txt_path = os.path.join("source_texts", txt_filename)
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(txt_content)

    print(f"完了: {html_file} / source_texts/{txt_filename} を更新しました")


def main():
    now = datetime.now()
    fetched_at = now.strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{fetched_at}] ニュース更新開始")

    for category in CATEGORY_CONFIG.keys():
        process_category(category, now)

    print(f"\n[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] 全カテゴリ完了")


if __name__ == "__main__":
    main()