import os
import json
import feedparser
import anthropic
from datetime import datetime
from dotenv import load_dotenv

# 実行ディレクトリを固定
os.chdir(os.path.dirname(os.path.abspath(__file__)))
load_dotenv()

RSS_FEEDS = [
    "https://techcrunch.com/category/artificial-intelligence/feed/",
    "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    "https://venturebeat.com/category/ai/feed/",
    "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
]

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>今日のAIニュース - {date}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      background: #0d1117;
      color: #e6edf3;
      font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.7;
      padding: 2rem 1rem;
    }}
    header {{ text-align: center; margin-bottom: 3rem; }}
    header h1 {{
      font-size: 2rem;
      font-weight: 700;
      background: linear-gradient(135deg, #58a6ff, #bc8cff);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      margin-bottom: 0.5rem;
    }}
    header p.date {{ color: #8b949e; font-size: 0.95rem; }}
    .container {{ max-width: 860px; margin: 0 auto; }}
    .news-grid {{ display: grid; gap: 1.2rem; }}
    .card {{
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 12px;
      padding: 1.4rem 1.6rem;
      transition: border-color 0.2s, transform 0.2s;
    }}
    .card:hover {{ border-color: #58a6ff; transform: translateY(-2px); }}
    .card-header {{ display: flex; align-items: center; gap: 0.8rem; margin-bottom: 0.6rem; }}
    .badge {{
      background: linear-gradient(135deg, #1f6feb, #388bfd);
      color: #fff;
      font-size: 0.75rem;
      font-weight: 700;
      padding: 0.2rem 0.6rem;
      border-radius: 20px;
      white-space: nowrap;
    }}
    .card h2 {{ font-size: 1.05rem; font-weight: 600; color: #f0f6fc; }}
    .card p {{ color: #8b949e; font-size: 0.92rem; margin-top: 0.3rem; }}
    .card p + p {{ margin-top: 0.2rem; }}
    .card a.source {{
      display: inline-block;
      margin-top: 0.5rem;
      color: #58a6ff;
      font-size: 0.8rem;
      text-decoration: none;
    }}
    .card a.source:hover {{ text-decoration: underline; }}
    .summary-section {{
      background: #161b22;
      border: 1px solid #30363d;
      border-left: 4px solid #bc8cff;
      border-radius: 12px;
      padding: 1.4rem 1.6rem;
      margin-top: 2rem;
    }}
    .summary-section h3 {{ font-size: 1.1rem; color: #bc8cff; margin-bottom: 0.8rem; }}
    .summary-section p {{ color: #8b949e; font-size: 0.93rem; margin-bottom: 0.4rem; }}
    footer {{ text-align: center; margin-top: 3rem; color: #484f58; font-size: 0.8rem; }}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>今日のAIニュース</h1>
      <p class="date">{date}</p>
    </header>
    <div class="news-grid">
{cards}
    </div>
    <div class="summary-section">
      <h3>まとめ</h3>
{summary_paragraphs}
    </div>
    <footer>
      <p>今日のAIニュース &mdash; {date} &copy; Auto-generated by Claude</p>
    </footer>
  </div>
</body>
</html>
"""


def fetch_articles(max_per_feed=8):
    articles = []
    for url in RSS_FEEDS:
        print(f"  Fetching: {url}")
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:max_per_feed]:
                title = entry.get("title", "").strip()
                summary = entry.get("summary", entry.get("description", "")).strip()
                link = entry.get("link", "")
                if title:
                    articles.append({"title": title, "summary": summary[:300], "url": link})
        except Exception as e:
            print(f"  [ERROR] Failed to fetch {url}: {e}")
    return articles


def generate_news_with_claude(articles):
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY が設定されていません。.env を確認してください。")

    client = anthropic.Anthropic(api_key=api_key)
    today = datetime.now().strftime("%Y年%m月%d日")

    articles_text = "\n".join(
        f"[{i+1}] タイトル: {a['title']}\n    概要: {a['summary']}\n    URL: {a['url']}"
        for i, a in enumerate(articles)
    )

    prompt = f"""あなたはAIニュースの専門ライターです。
以下の英語記事リストを参考に、{today}の「今日のAIニュース」を日本語で20本作成してください。

【記事リスト】
{articles_text}

【出力形式】
以下のJSON配列のみを出力してください（コードブロック不要）:
[
  {{
    "number": 1,
    "title": "ニュースタイトル（日本語）",
    "points": ["要点1（日本語）", "要点2（日本語）", "要点3（日本語）"],
    "url": "元記事URL"
  }},
  ...
]

【ルール】
- タイトルは日本語で簡潔に（30文字以内）
- 各ニュースの要点は2〜4個の日本語箇条書き
- 重要度・注目度の高いものを優先して選ぶ
- 最後に "summary" キーで3文程度の今日全体のまとめも追加:
  {{"summary": ["まとめ文1", "まとめ文2", "まとめ文3"]}}
"""

    print("  Claude APIに問い合わせ中...")
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=8192,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = message.content[0].text.strip()

    # JSON部分を抽出（```json ... ``` で囲まれている場合も対応）
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    data = json.loads(raw)
    return data


def build_html(news_items, summary_lines, date_str):
    cards_html = ""
    for item in news_items:
        num = str(item.get("number", "")).zfill(2)
        title = item.get("title", "")
        points = item.get("points", [])
        url = item.get("url", "")

        points_html = "\n".join(f'        <p>{p}</p>' for p in points)
        source_html = f'\n        <a class="source" href="{url}" target="_blank">元記事を読む →</a>' if url else ""

        cards_html += f"""\
      <div class="card">
        <div class="card-header">
          <span class="badge">{num}</span>
          <h2>{title}</h2>
        </div>
{points_html}{source_html}
      </div>\n"""

    summary_paragraphs = "\n".join(f'      <p>{s}</p>' for s in summary_lines)

    return HTML_TEMPLATE.format(
        date=date_str,
        cards=cards_html,
        summary_paragraphs=summary_paragraphs,
    )


def build_txt(news_items, summary_lines, date_str):
    lines = []
    lines.append("=" * 64)
    lines.append(f" 今日のAIニュース - {date_str}")
    lines.append("=" * 64)
    lines.append("")

    for item in news_items:
        num = item.get("number", "")
        title = item.get("title", "")
        points = item.get("points", [])
        url = item.get("url", "")

        lines.append(f"【{num}】{title}")
        for p in points:
            lines.append(f"  {p}")
        if url:
            lines.append(f"  → {url}")
        lines.append("")

    lines.append("=" * 64)
    lines.append(" まとめ")
    lines.append("=" * 64)
    lines.append("")
    for s in summary_lines:
        lines.append(s)
    lines.append("")
    lines.append("=" * 64)

    return "\n".join(lines)


def main():
    now = datetime.now()
    date_str = now.strftime("%Y年%m月%d日（%a）").replace(
        "Mon", "月").replace("Tue", "火").replace("Wed", "水").replace(
        "Thu", "木").replace("Fri", "金").replace("Sat", "土").replace("Sun", "日")

    print(f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] AIニュース更新開始")

    print("RSSフィード取得中...")
    articles = fetch_articles()
    print(f"  合計 {len(articles)} 件の記事を取得")

    if not articles:
        print("[ERROR] 記事を取得できませんでした。既存ファイルを保持します。")
        return

    print("Claude APIでニュース生成中...")
    data = generate_news_with_claude(articles)

    # newsとsummaryを分離
    news_items = [item for item in data if isinstance(item, dict) and "title" in item]
    summary_obj = next((item for item in data if isinstance(item, dict) and "summary" in item and "title" not in item), None)
    summary_lines = summary_obj.get("summary", ["本日も多くのAIニュースが報告されました。"]) if summary_obj else ["本日も多くのAIニュースが報告されました。"]

    print(f"  {len(news_items)} 件のニュースを生成")

    html_content = build_html(news_items, summary_lines, date_str)
    txt_content = build_txt(news_items, summary_lines, date_str)

    with open("ai.html", "w", encoding="utf-8") as f:
        f.write(html_content)
    with open("ai.txt", "w", encoding="utf-8") as f:
        f.write(txt_content)

    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] 完了: ai.html / ai.txt を更新しました")


if __name__ == "__main__":
    main()
